// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ8VXAJlIVoeaCHkzMXaGdnYNDW7QoZ-s',
    appId: '1:843331886089:web:7a63ca7f8a2202b257ecd8',
    messagingSenderId: '843331886089',
    projectId: 'datn-20cq-aiohs',
    authDomain: 'datn-20cq-aiohs.firebaseapp.com',
    storageBucket: 'datn-20cq-aiohs.appspot.com',
    measurementId: 'G-QLB45H6CD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjH26qXf_fIavKWHOuX8vLZXsAJGqrz40',
    appId: '1:843331886089:android:6d7617016fd6b30557ecd8',
    messagingSenderId: '843331886089',
    projectId: 'datn-20cq-aiohs',
    storageBucket: 'datn-20cq-aiohs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1Bt7e_w7aLaC5rl4YYczizNW3_HuCEA',
    appId: '1:843331886089:ios:0612b8aa0afe1a8357ecd8',
    messagingSenderId: '843331886089',
    projectId: 'datn-20cq-aiohs',
    storageBucket: 'datn-20cq-aiohs.appspot.com',
    androidClientId: '843331886089-4sa87imm81cbgd79mf9v03kq88lqj0dj.apps.googleusercontent.com',
    iosClientId: '843331886089-9pebse69sq7ccbfk8sjf42e03tcbq98t.apps.googleusercontent.com',
    iosBundleId: 'com.example.rmservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1Bt7e_w7aLaC5rl4YYczizNW3_HuCEA',
    appId: '1:843331886089:ios:d258cfa045330ac357ecd8',
    messagingSenderId: '843331886089',
    projectId: 'datn-20cq-aiohs',
    storageBucket: 'datn-20cq-aiohs.appspot.com',
    androidClientId: '843331886089-4sa87imm81cbgd79mf9v03kq88lqj0dj.apps.googleusercontent.com',
    iosClientId: '843331886089-0lhqs7oaa9tsnvf46dddajgdm8sa1cqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rmservice.RunnerTests',
  );
}
